const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.ScriptsInEvents.FolhaDeOverword2_Event8,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.ScriptsInEvents.FolhaDeOverword_Event10,
		C3.Plugins.Audio.Cnds.OnEnded
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Mosaico: 0},
	{Plataforma: 0},
	{steve: 0},
	{CentrarEm: 0},
	{camera: 0},
	{Toque: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Âncora: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Texto: 0},
	{Mouse: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Mosaico2: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{FonteDeSprites: 0},
	{MineRun: 0},
	{play: 0},
	{zombi: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{respawn: 0},
	{inicio: 0},
	{TemaMine: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{alexselect: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{BEMVINDOAONETHER: 0},
	{Sprite10: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Sprite11: 0},
	{Mosaico3: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Texto2: 0},
	{Sprite12: 0},
	{ghast: 0},
	{pxFire_Item: 0},
	{Teclado: 0},
	{Texto3: 0},
	{Sprite13: 0},
	{MineRun2: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	steve: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	MineRun: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	zombi: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	respawn: class extends self.ITextInstance {},
	inicio: class extends self.ITextInstance {},
	TemaMine: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	alexselect: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	BEMVINDOAONETHER: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	ghast: class extends self.ISpriteInstance {},
	pxFire_Item: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	MineRun2: class extends self.ISpriteInstance {}
}